CREATE TABLE IF NOT EXISTS cs.okta_user (
    id VARCHAR(50) PRIMARY KEY,
    created TIMESTAMPTZ,
    activated TIMESTAMPTZ,
    status VARCHAR(50),
    status_changed TIMESTAMPTZ,
    last_login TIMESTAMPTZ,
    last_updated TIMESTAMPTZ,
    password_changed TIMESTAMPTZ,
    login VARCHAR(100),
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    email VARCHAR(100),
    email_verified BOOL,
    second_email VARCHAR(100),
    second_email_verified BOOL,
    phone VARCHAR(100),
    phone_verified BOOL,
    second_phone VARCHAR(100),
    second_phone_verified BOOL,
    display_name TEXT,
    nickname TEXT,
    profile_url TEXT,
    title TEXT,
    user_type TEXT,
    preferred_language TEXT,
    perferred_timezone TEXT,
    locale TEXT,
    timezone TEXT,
    organization TEXT,
    cost_center TEXT,
    department TEXT,
    division TEXT,
    employee_number TEXT,
    employee_type TEXT,
    manager TEXT,
    manager_id TEXT,
    primary_relationship TEXT,
    UNIQUE(id, login, email, second_email)
);