# https://developer.okta.com/docs/reference/api/users/#user-properties
# https://developer.okta.com/docs/reference/api/schemas/#user-profile-base-subschema

CREATE TABLE cs.okta_user (
    id STRING PRIMARY KEY,
    created TIME,
    activated TIME,
    status STRING,
    status_changed TIME,
    last_login TIME,
    last_updated TIME,
    password_changed TIME,
    login STRING,
    first_name STRING,
    last_name STRING,
    email STRING,
    email_verified BOOL,
    second_email STRING,
    second_email_verified BOOL,
    phone STRING,
    phone_verified BOOL,
    second_phone STRING,
    second_phone_verified BOOL,
    display_name STRING,
    nickname STRING,
    profile_url STRING,
    title STRING,
    user_type STRING,
    preferred_language STRING,
    perferred_timezone STRING,
    locale STRING,
    timezone STRING,
    organization STRING,
    cost_center STRING,
    department STRING,
    division STRING,
    employee_number STRING,
    employee_type STRING,
    manager STRING,
    manager_id STRING,
    primary_relationship STRING,
    UNIQUE(id, login, email, second_email)
);
