# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "circulate-state-dev"
    dynamodb_table = "circulate-dev-lock-table"
    encrypt        = true
    key            = "./terraform.tfstate"
    region         = "us-east-2"
  }
}
